{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d8d7ec28-a607-4654-b8c8-5b27787b1cce",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/home/bosser/anaconda3/lib/python3.12/runpy.py\", line 198, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/runpy.py\", line 88, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/asyncio/base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/asyncio/base_events.py\", line 1986, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_45960/2947391713.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/pandas/__init__.py\", line 26, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/pandas/compat/__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/pandas/compat/pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.2.3 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m~/anaconda3/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py:44\u001b[0m, in \u001b[0;36m__getattr__\u001b[0;34m(attr_name)\u001b[0m\n\u001b[1;32m     39\u001b[0m     \u001b[38;5;66;03m# Also print the message (with traceback).  This is because old versions\u001b[39;00m\n\u001b[1;32m     40\u001b[0m     \u001b[38;5;66;03m# of NumPy unfortunately set up the import to replace (and hide) the\u001b[39;00m\n\u001b[1;32m     41\u001b[0m     \u001b[38;5;66;03m# error.  The traceback shouldn't be needed, but e.g. pytest plugins\u001b[39;00m\n\u001b[1;32m     42\u001b[0m     \u001b[38;5;66;03m# seem to swallow it and we should be failing anyway...\u001b[39;00m\n\u001b[1;32m     43\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(msg \u001b[38;5;241m+\u001b[39m tb_msg)\n\u001b[0;32m---> 44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(msg)\n\u001b[1;32m     46\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(_multiarray_umath, attr_name, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m     47\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mImportError\u001b[0m: \nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.2.3 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"/home/bosser/anaconda3/lib/python3.12/runpy.py\", line 198, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/runpy.py\", line 88, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/asyncio/base_events.py\", line 641, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/asyncio/base_events.py\", line 1986, in _run_once\n",
      "    handle._run()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/asyncio/events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/tmp/ipykernel_45960/2947391713.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/pandas/__init__.py\", line 49, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/pandas/core/api.py\", line 9, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/pandas/core/dtypes/dtypes.py\", line 24, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"/home/bosser/anaconda3/lib/python3.12/site-packages/pyarrow/__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "ImportError",
     "evalue": "\nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.2.3 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "File \u001b[0;32m~/anaconda3/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py:44\u001b[0m, in \u001b[0;36m__getattr__\u001b[0;34m(attr_name)\u001b[0m\n\u001b[1;32m     39\u001b[0m     \u001b[38;5;66;03m# Also print the message (with traceback).  This is because old versions\u001b[39;00m\n\u001b[1;32m     40\u001b[0m     \u001b[38;5;66;03m# of NumPy unfortunately set up the import to replace (and hide) the\u001b[39;00m\n\u001b[1;32m     41\u001b[0m     \u001b[38;5;66;03m# error.  The traceback shouldn't be needed, but e.g. pytest plugins\u001b[39;00m\n\u001b[1;32m     42\u001b[0m     \u001b[38;5;66;03m# seem to swallow it and we should be failing anyway...\u001b[39;00m\n\u001b[1;32m     43\u001b[0m     sys\u001b[38;5;241m.\u001b[39mstderr\u001b[38;5;241m.\u001b[39mwrite(msg \u001b[38;5;241m+\u001b[39m tb_msg)\n\u001b[0;32m---> 44\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mImportError\u001b[39;00m(msg)\n\u001b[1;32m     46\u001b[0m ret \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mgetattr\u001b[39m(_multiarray_umath, attr_name, \u001b[38;5;28;01mNone\u001b[39;00m)\n\u001b[1;32m     47\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m ret \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mImportError\u001b[0m: \nA module that was compiled using NumPy 1.x cannot be run in\nNumPy 2.2.3 as it may crash. To support both 1.x and 2.x\nversions of NumPy, modules must be compiled with NumPy 2.0.\nSome module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n\nIf you are a user of the module, the easiest solution will be to\ndowngrade to 'numpy<2' or try to upgrade the affected module.\nWe expect that some modules will need time to support NumPy 2.\n\n"
     ]
    }
   ],
   "source": [
    "import mysql.connector\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from unidecode import unidecode\n",
    "from sklearn.impute import KNNImputer\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "import joblib\n",
    "import dill\n",
    "import pickle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0a8f5b14-192d-4cd5-a4d6-e8cea655ae29",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_45960/3196037239.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_numeros = pd.read_sql(query_numero, db)\n",
      "/tmp/ipykernel_45960/3196037239.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.\n",
      "  df_general = pd.read_sql(query_ofertas, db)\n"
     ]
    }
   ],
   "source": [
    "config = toml.load(\"../.streamlit/secrets.toml\")\n",
    "db_config = config[\"database\"]\n",
    "\n",
    "db = mysql.connector.connect(host=db_config[\"host\"],\n",
    "                             user=db_config[\"user\"],\n",
    "                             password=db_config[\"password\"],\n",
    "                             database=db_config[\"database\"]) \n",
    "\n",
    "# Primera consulta: Obtener el número de tecnologías y habilidades por oferta\n",
    "query_numero = \"\"\"\n",
    "SELECT \n",
    "    o.id_oferta,\n",
    "    o.ciudad,\n",
    "    COUNT(DISTINCT tr.tec_id) AS num_tecnologias,\n",
    "    COUNT(DISTINCT hr.hab_id) AS num_habilidades\n",
    "FROM \n",
    "    ofertas o\n",
    "LEFT JOIN \n",
    "    tecnologias_relacion tr ON o.id_oferta = tr.id_oferta\n",
    "LEFT JOIN \n",
    "    habilidades_relacion hr ON o.id_oferta = hr.id_oferta\n",
    "GROUP BY \n",
    "    o.id_oferta, o.ciudad;\n",
    "\"\"\"\n",
    "df_numeros = pd.read_sql(query_numero, db)\n",
    "\n",
    "# Segunda consulta: Obtener todas las ofertas\n",
    "query_ofertas = \"SELECT * FROM ofertas;\"\n",
    "df_general = pd.read_sql(query_ofertas, db)\n",
    "\n",
    "db.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "c5471640-eed6-4946-a0c5-f4ace5e086c2",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_numeros.rename(columns={\"id_oferta\": \"id\"}, inplace=True)\n",
    "df_general.rename(columns={\"id_oferta\": \"id\"}, inplace=True)\n",
    "df_general = pd.merge(df_general, df_numeros, on=\"id\", how=\"left\")\n",
    "df_general[\"salario_media\"] = (df_general[\"salario_desde\"] + df_general[\"salario_hasta\"]) / 2\n",
    "df_general[\"variable_booleano\"] = ~df_general[\"variabe\"].isna() & (df_general[\"variabe\"] != 0)\n",
    "columna_id = df_general[\"id\"]\n",
    "df_general = df_general.drop(columns=[\"ciudad_x\", \"id\", \"empresa\", \n",
    "                                      \"titulo\", \"url\", \"timestamp\", \n",
    "                                      \"fecha_publicacion\", \"oferta_activada\", \n",
    "                                      \"cvs_inscritos\", \"imprescindible_residir\", \n",
    "                                      \"vacantes\"])\n",
    "df_general.rename(columns={\"variabe\": \"variable\"}, inplace=True)\n",
    "df_general.rename(columns={\"ciudad_y\": \"ciudad\"}, inplace=True)\n",
    "df_general[\"ciudad\"] = df_general[\"ciudad\"].str.title()\n",
    "df_general = df_general.drop(columns=[\"salario_desde\", \"salario_hasta\"])\n",
    "col = df_general.pop(\"salario_media\")\n",
    "df_general.insert(4, \"salario_media\", col)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ac0a5295-2a34-4511-9a84-b208b5c7576b",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Creamos encoder para transformar todas las columnas categóricas a numéricas.\n",
    "\n",
    "encoder = {\n",
    "    \"salario_media\": None,\n",
    "    \"variable\": lambda df: df[\"variable\"].fillna(0),\n",
    "    \"variable_booleano\": lambda df: df[\"variable\"].apply(lambda x: 1 if x != 0 else 0),\n",
    "    \"vacaciones\": lambda df: df[\"vacaciones\"].mode()[0] if not df[\"vacaciones\"].mode().empty else 0,\n",
    "    \"teletrabajo\": {\"Presencial\": 0, \"Hibrido\": 1, \"Remoto\": 2},\n",
    "    \"jornada_tipo\": {\"Por Horas\": 1,\n",
    "                     \"Media Jornada\": 2,\n",
    "                     \"Turno Rotatorio\": 3,\n",
    "                     \"Intensiva Tarde\": 4,\n",
    "                     \"Jornada Completa\": 4.1,\n",
    "                     \"Intensiva Mañana\": 4.3,\n",
    "                     \"Jornada Completa Flexible\": 4.4},\n",
    "\n",
    "    \"turno_continuo\": None,\n",
    "    \"funciones\": lambda df: df[\"funciones\"].map({cat: i for i, cat in enumerate(df[\"funciones\"].dropna().unique())}),\n",
    "    \"contrato_tipo\": {\"A determinar\": 1,\n",
    "                      \"Prácticas\": 2,\n",
    "                      \"Obra o servicio\": 3,\n",
    "                      \"Temporal\": 4,\n",
    "                      \"Freelance/Autónomo\": 5,\n",
    "                      \"Indefinido\": 6},\n",
    "    \"nivel_profesional\": {\"Prácticas / Beca\": 1,\n",
    "                          \"Empleado\": 5,\n",
    "                          \"Mando Intermedio\": 20,\n",
    "                          \"Especialista\": 30,\n",
    "                          \"Director / Gerente\": 40,\n",
    "                          \"Administrador / Consejero\": 50},\n",
    "    \"formacion_minima\": {\"Sin estudios\": 15,\n",
    "                         \"E.S.O. (Educación Secundaria Obligatoria)\": 16,\n",
    "                         \"FP1\": 18,\n",
    "                         \"Grado Medio\": 18,\n",
    "                         \"Bachillerato/COU\": 18.5,\n",
    "                         \"Certificado de Profesionalidad\": 19,\n",
    "                         \"Otros títulos, certificaciones y carnets\": 19.4,\n",
    "                         \"Otra Formación Tecnológica\": 19.8,\n",
    "                         \"FP2/Grado Superior\": 20,\n",
    "                         \"Diplomado\": 21,\n",
    "                         \"Ingeniero Técnico\": 21.5,\n",
    "                         \"Grado EEES (Bolonia)\": 22,\n",
    "                         \"Licenciado\": 23,\n",
    "                         \"Ingeniero Superior\": 23.5,\n",
    "                         \"Postgrado EEES (Máster)\": 24,\n",
    "                         \"Doctorado\": 28},\n",
    "    \"personas_a_cargo\": lambda df: df[\"personas_a_cargo\"].fillna(0),\n",
    "    \"experiencia\": {\"Sin Experiencia\": 1,\n",
    "                    \"Menos de un año\": 2,\n",
    "                    \"1 año\": 2,\n",
    "                    \"2 años\": 5,\n",
    "                    \"3 años\": 5,\n",
    "                    \"3-5 años\": 5,\n",
    "                    \"default\": 10},\n",
    "    \"num_tecnologias\": None,\n",
    "    \"num_habilidades\": None,\n",
    "    \"ciudad\": lambda df: df[\"ciudad\"].map({cat: i for i, cat in enumerate(df[\"ciudad\"].dropna().unique())})}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b299d122-69c1-4221-a6ec-bc580d0e3a77",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Codificamos el df\n",
    "\n",
    "for columna, transformacion in encoder.items():\n",
    "    if columna not in df_general.columns:\n",
    "        print(f\"Columna {columna} no encontrada en el DataFrame, omitiendo transformación.\")\n",
    "        continue\n",
    "    if transformacion is None:\n",
    "        continue\n",
    "    elif callable(transformacion):\n",
    "        df_general[columna] = transformacion(df_general)\n",
    "    elif isinstance(transformacion, dict):\n",
    "        df_general[columna] = df_general[columna].map(transformacion)\n",
    "    else:\n",
    "        df_general[columna] = transformacion  # En caso de que sea un valor constante"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "7d35aa82-d3dc-4967-92c3-d119906d0dd6",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "#Escalamos los datos con MinMaxScaler\n",
    "\n",
    "scaler = MinMaxScaler()\n",
    "df_scaled = scaler.fit_transform(df_general)  # Esto devuelve un numpy array\n",
    "df_scaled = pd.DataFrame(df_scaled, columns=df_general.columns) # Convertimos a df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "fd898345-aa0d-4734-b991-3eaa638f2a86",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "#Imputamos datos faltantes. Y guardamos en csv el df imputado con el id de nuevo.\n",
    "\n",
    "imputer = KNNImputer(n_neighbors=3)\n",
    "df_imputado = imputer.fit_transform(df_scaled)\n",
    "df_imputado = pd.DataFrame(df_imputado, columns=df_scaled.columns)\n",
    "df_imputado[\"id\"] = columna_id\n",
    "df_imputado.to_csv(\"df_imputado_clustering.csv\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "c1992270-a502-4ffc-85fc-ed1d4290782c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Guardamos el encoder, el scaler y el imputer en pickles\n",
    "\n",
    "with open(\"encoder_clustering.pkl\", \"wb\") as f:\n",
    "    dill.dump(encoder, f)\n",
    "\n",
    "with open(\"scaler_clustering.pkl\", \"wb\") as f:\n",
    "    pickle.dump(scaler, f)\n",
    "\n",
    "with open(\"imputer_clustering.pkl\", \"wb\") as f:\n",
    "    pickle.dump(imputer, f)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "171d0582-c40a-4755-baad-7c67e53da7fa",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
